### ISSUE TITLE
Meeting Mercoledì

### ISSUE THREAD

**Issue by stoffie** [ict4g/ror-mariecurie-2016#3]
Confermate che il meeting è alle 10.30?

**Comment by pbmolini** [comment]
Domani alle 10:00 Aaron ed io siamo in un meeting con Lorenzo Rigato e Michele Bof

Andrebbe bene se spostassimo al pomeriggio? Tipo alle 15:30 perché alle 14:30 ho uno stagista

Fatemi sapere

-- 
Pietro
Sent with Airmail

Il giorno 19 gennaio 2016 @ 13:42:10, Damiano Stoffie (notifications@github.com) ha scritto:

Confermate che il meeting è alle 10.30?

**Comment by stoffie** [comment]
Per me andrebbe bene, inoltro anche a Zen :)
